services:
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce:latest
    ports:
        - 9443:9443
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /vault/containers/portainer/data:/data
